color0 #e0e8eb
color1 #fd4663
color2 #229cc3
color3 #2949a3
color4 #2f194d
color5 #176882
color6 #1b357e
color7 #181a1b
color8 #5d8b9b
color9 #fd4663
color10 #229cc3
color11 #2949a3
color12 #2f194d
color13 #176882
color14 #1b357e
color15 #181a1b

cursor                #181a1b
cursor_text_color     #e0e8eb
background            #e0e8eb
foreground            #181a1b
selection_foreground  #505658
selection_background  #bbcdd3
active_border_color   #229cc3
inactive_border_color #bbcdd3
url_color             #229cc3

active_tab_foreground   #f9fafa
active_tab_background   #229cc3
inactive_tab_foreground #505658
inactive_tab_background #bbcdd3
cursor_trail_color      #505658
