color0 #281b15
color1 #fd4663
color2 #ecab91
color3 #d65c7c
color4 #cddf9e
color5 #ecac92
color6 #e996ac
color7 #f3f2f2
color8 #756560
color9 #fd4663
color10 #ecab91
color11 #d65c7c
color12 #cddf9e
color13 #ecac92
color14 #e996ac
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #281b15
background            #281b15
foreground            #f3f2f2
selection_foreground  #b6b1af
selection_background  #35241c
active_border_color   #ecab91
inactive_border_color #35241c
url_color             #ecab91

active_tab_foreground   #251c18
active_tab_background   #ecab91
inactive_tab_foreground #b6b1af
inactive_tab_background #35241c
cursor_trail_color      #b6b1af
