background                #000000
foreground                #ff00ff
cursor                    #ff00ff
selection_background      #6b0080
selection_foreground      #ff00ff
active_tab_background     #ff00ff
inactive_tab_background   #1e0a2e
inactive_tab_foreground   #ff00ff
