background                #000000
foreground                #ff0000
cursor                    #ff0000
selection_background      #570000
selection_foreground      #ff0000
active_tab_background     #ff0000
inactive_tab_background   #1a0000
inactive_tab_foreground   #ff0000
