background                #000000
foreground                #ffff00
cursor                    #ffff00
selection_background      #5a4800
selection_foreground      #ffff00
active_tab_background     #ffff00
inactive_tab_background   #1a1400
inactive_tab_foreground   #ffff00
