background                #000000
foreground                #8f6200
cursor                    #8f6200
selection_background      #362501
selection_foreground      #8f6200
active_tab_background     #8f6200
inactive_tab_background   #110b00
inactive_tab_foreground   #8f6200
