# #################### #
#   PROGRAMAS PADRÃO   #
# #################### #

$terminal = kitty
$fileManager = nautilus
$tfileManager = kitty yazi
$browser = zen-browser
$live =  obs
$editor = kitty nvim
$music = spotify

# ############# #
#   AUTOSTART   #
# ############# #
#
exec-once = swaync -c ~/.config/swaync/config.json -s ~/.config/swaync/style.css
exec-once = hypridle
exec-once = hyprctl setcursor $cursor $cursor_size
