# #################### #
#   PROGRAMAS PADRÃO   #
# #################### #

source = ~/.config/hypr/modules/swww.conf
source = ~/.config/hypr/modules/clipboard.conf

$terminal = kitty
$fileManager = nautilus
$tfileManager = kitty yazi
$browser = zen-browser
$live =  obs
$editor = kitty nvim
$music = spotify
$themeSelector = ~/.config/rofi/scripts/theme-selector/theme.sh
$menu = ~/.config/rofi/launchers/snowy/launcher.sh

# ############# #
#   AUTOSTART   #
# ############# #

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = awww-daemon
exec-once = swaync -c ~/.config/swaync/config.json -s ~/.config/swaync/style.css
exec-once = hypridle
exec-once = hyprctl setcursor $cursor $cursor_size
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # Para poder rodar apps gráficos tipo VSCode com sudo
