# ############################ #
# Classes de Janela (Cuidado!) #
# ############################ #
windowrule {
    name = Floating-PiP
    match:title = Picture-in-Picture

    float = true
    pin = true
    size = 480 270
    move = 800 100
}

windowrule {
    name = Fetch
    match:class = fastfetch-widget

    float = true
    size = 662 280
    move = 39 86
    no_initial_focus = on
}

windowrule {
    name = Salvar_Partitura_Centralizado
    match:title = Salvar partitura

    move = 283 93
  }
