$primary = rgb(ecab91)
$surface = rgb(281b15)
$secondary = rgb(d65c7c)
$error = rgb(fd4663)
$tertiary = rgb(cddf9e)
$surface_lowest = rgb(140d0b)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
