hl.config({ autogenerated = false })

require("input")
require("appearence")
require("windows")
require("monitors")

-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
	hl.exec_cmd(terminal)
	hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("hyprctl setcursor rose-pine-hyprcursor 24")
	hl.exec_cmd("/home/yasmin/.local/bin/sync-theme.sh")
end)

-----------------------
----- PERMISSIONS -----
-----------------------

hl.env("WLR_DRM_DEVICES", "/dev/dri/card0:/dev/dri/card1")

hl.config({
	ecosystem = {
		enforce_permissions = true,
	},
})

hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-------------------
----- GENERAL -----
-------------------

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 20,

		border_size = 0,

		resize_on_border = true,

		allow_tearing = false,

		layout = "dwindle",
	},

	decoration = {
		rounding = 10,
		rounding_power = 2,

		active_opacity = 0.9,
		inactive_opacity = 0.8,

		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},

		blur = {
			enabled = true,
			size = 2,
			passes = 4,
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = true,
	},
})

hl.config({
	dwindle = {
		preserve_split = true,
	},
})

hl.config({
	master = {
		new_status = "master",
	},
})

hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

hl.config({
	misc = {
		force_default_wallpaper = 0,
		disable_hyprland_logo = true,
	},
})

hl.config({
	cursor = {
		no_hardware_cursors = 1,
		enable_hyprcursor = true,
	},
})
