background                #000000
foreground                #ff8400
cursor                    #ff8400
selection_background      #7a2e00
selection_foreground      #ff8400
active_tab_background     #ff8400
inactive_tab_background   #1f0e00
inactive_tab_foreground   #ff8400
