background                #000000
foreground                #0000ff
cursor                    #0000ff
selection_background      #001f85
selection_foreground      #0000ff
active_tab_background     #0000ff
inactive_tab_background   #050d2e
inactive_tab_foreground   #0000ff
