background                #000000
foreground                #00ffff
cursor                    #00ffff
selection_background      #00b8b8
selection_foreground      #00ffff
active_tab_background     #00ffff
inactive_tab_background   #183a43
inactive_tab_foreground   #00ffff
