background                #000000
foreground                #ff00f7
cursor                    #ff00f7
selection_background      #7a0078
selection_foreground      #ff00f7
active_tab_background     #ff00f7
inactive_tab_background   #1f001e
inactive_tab_foreground   #ff00f7
