background                #000000
foreground                #9000ff
cursor                    #9000ff
selection_background      #480080
selection_foreground      #9000ff
active_tab_background     #9000ff
inactive_tab_background   #0d0020
inactive_tab_foreground   #9000ff
